name: Build amd64 Masscan 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libpcap-dev

      - name: Build amd64 binary
        run: |
          make CC="gcc -m64" CFLAGS="-m64 -O2" LDFLAGS="-m64"

      - name: Verify binary architecture
        run: |
          file bin/masscan | grep "64-bit"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: masscan-linux-amd64
          path: bin/masscan




 
